### ISSUE TITLE
Substance use workplan

### ISSUE THREAD

**Issue by lanejames35** [WatDurCodeGroup/ribosome#1]
As the title suggests, I'm working on substance use indicators first. Below is a list of the macro I'll be working on.
* e-cigarettes
* Exposure to second-hand smoke
* Underage drinking
* Cannabis use, frequency of

**Comment by lanejames35** [comment]
:heavy_check_mark: Exposure to second-hand smoke is done.
:question: I'm likely dropping e-cigarettes, because there's only 44 in the numerator. If it's valuable to Waterloo, I can keep it.

**Comment by lanejames35** [comment]
These are done. @JakeTennant, do you need e-cigarettes? If not, I'll close this issue.

**Comment by JakeTennant** [comment]
Hmm. I know there's a vaping data request in the pipeline for us. Although if the numerator is that low, I wonder how accurate it is... Feel free to close it. If we end up using it, I can add the code later.
